openapi: 3.0.1
info:
  title: Product API
  description: API for retrieving products based on the user's ID.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Local server
paths:
  /product:
    get:
      summary: Retrieve user products
      description: Fetches a list of products associated with the authenticated user, including their details and attachments.
      operationId: getUserProducts
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successfully retrieved the list of products.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Products retrieved successfully."
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 2
                        name:
                          type: string
                          example: "Tenda Ajinium"
                        description:
                          type: string
                          example: "Tenda buat anak2 dari pendiri 1cak"
                        price:
                          type: number
                          format: float
                          example: 1000
                        stock:
                          type: integer
                          example: 0
                        category:
                          type: string
                          example: "alat"
                        created_at:
                          type: string
                          format: date-time
                          example: "2024-12-19T21:19:50.154Z"
                        updated_at:
                          type: string
                          format: date-time
                          example: "2024-12-19T21:19:50.154Z"
                        attachments:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                                example: 1
                              link:
                                type: string
                                example: "https://ik.imagekit.io/dhzfyg2xn/cirata_2_yzVIs9M5h.jpeg"
        '400':
          description: Bad request, invalid user ID format or type.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Invalid user ID format."
        '401':
          description: Unauthorized. No valid Bearer token found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Unauthorized. User ID not found."
        '500':
          description: Internal server error while retrieving products.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Failed to retrieve products."
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
